package com.smartycoder.visualisation;

import com.smartycoder.ui.DrawMultilineText;
import com.smartycoder.ui.DrawPolygon;
import com.smartycoder.ui.VisualisationUtil;
import org.locationtech.jts.geom.Coordinate;
import org.locationtech.jts.geom.GeometryFactory;
import org.locationtech.jts.geom.Polygon;

import java.awt.Color;

/**
 *
 * @see https://www.smartycoder.com
 *
 */
public class DifferenceAreaCalculation {

    public static void main(String[] args) {
        GeometryFactory geometryFactory = new GeometryFactory();

        Coordinate[] coordinates = {
                new Coordinate(150, 60),
                new Coordinate(325, 180),
                new Coordinate(90, 150),
                new Coordinate(150, 60),
        };
        Coordinate[] coordinates2 = {
                new Coordinate(210, 120),
                new Coordinate(350, 120),
                new Coordinate(400, 210),
                new Coordinate(250, 300),
                new Coordinate(180, 150),
                new Coordinate(210, 120),
        };
        Polygon bluePolygon = geometryFactory.createPolygon(coordinates);
        Polygon yellowPolygon = geometryFactory.createPolygon(coordinates2);
        Polygon differencePolygon = (Polygon) yellowPolygon.difference(bluePolygon);

        VisualisationUtil.show(
                "JTS Visualisation - Difference Area Calculation",
                new DrawPolygon(differencePolygon, null, VisualisationUtil.colorWithAlpha(Color.GREEN, 160), null),
                new DrawMultilineText("The polygon generated by the difference.", 60, 330, Color.WHITE)
        );
    }

}
